[pytest]
testpaths = tests deploy/h265-transcoder/tests
pythonpath = solution
python_files = test_*.py
addopts = -ra
filterwarnings =
    ignore::DeprecationWarning
    ignore::DeprecationWarning:starlette.*
